# permissions for end users to edit tls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tls-editor-role
rules:
- apiGroups:
  - gateway.kusk.io
  resources:
  - tls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.kusk.io
  resources:
  - tls/status
  verbs:
  - get
